#!/usr/bin/env bash
# FizzBuzz
# Displays numbers from 1 to 100 in list format.
#   Displays "FizzBuzz" when the number is a multiple of 3 and 5.
#   Displays "Fizz" when the number is a multiple of 3.
#   Displays "Buzz" when the number is a multiple of 5.
#   Otherwise, displays the numbers

COUNTER=1
while [ $COUNTER -lt 101 ]
do
    if [ $((COUNTER%15)) = 0 ]
    then
        echo "FizzBuzz"
    elif [ $((COUNTER%3)) = 0 ]
    then
        echo "Fizz"
    elif [ $((COUNTER%5)) = 0 ]
    then
        echo "Buzz"
    else
        echo "$COUNTER"
    fi
    COUNTER=$((COUNTER+1))
done
